[book]
authors = ["ritchie46"]
language = "en"
multilingual = false
src = "src"
title = "Polars - User Guide"

[output.html]
default-theme = "Ayu"
mathjax-support = true

[output.html.fold]
enable = false
level = 1

# custom preprocessor to insert the reference guide links
[preprocessor.replace]
command = "python preprocessor/replace.py"
