[book]
authors = ["ritchie46"]
language = "en"
multilingual = false
src = "src"
title = "Polars - Python Reference Guide"

[output.html]
default-theme = "Ayu"
mathjax-support = true
additional-css = ["theme/css/style.css"]
additional-js = ["theme/js/index.js"]

[output.html.fold]
enable = true
level = 0
