[book]
authors = ["ritchie46"]
language = "en"
multilingual = false
src = "src"
title = "polars-book"

[output.html]
default-theme = "Ayu"
mathjax-support = true

#[output.linkcheck] # validate links

[output.html.fold]
# toggle this to fold side tabs
enable = true
level = 1

# custom preprocessor to insert the API link
[preprocessor.replace]
command = "python3 preprocessor/replace.py"
replace_token = "POLARS_API_LINK"
substitute = "https://ritchie46.github.io/polars/python/polars"
