name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Set up Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - run: find docs/src/python -type f | xargs -n 1 bash -c 'python -W error $0 || exit 255'

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install black==23.7.0
      - run: black --check .

  rome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install --save-dev --save-exact rome
      - run: npx rome format docs/src/node/

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Polars
        run: npm i -s nodejs-polars
      - name: Install rng
        run: npm i -s chance
      - name: Run code snippets
        run: find docs/src/ -name "*.js" | xargs -n 1 sh -c 'node $0 || exit 255'
