name: codeblocks 
on:
  push:
    branches:
      - master 
      - main
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r polars[numpy]
      - run: find docs/src/ -name "*.py" | xargs -n 1 sh -c 'python $0 || exit 255'
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Polars 
        run: npm i -s nodejs-polars
      - name: Run code snippets
        run: find docs/src/ -name "*.js" | xargs -n 1 sh -c 'node $0 || exit 255'